# Generated by Django 2.2.1 on 2019-05-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_profie_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profie_picture',
            new_name='profile_picture',
        ),
    ]
